on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install ruff
      - name: Run Ruff
        run: ruff check

  typecheck:
    name: Type-check with mypy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install project dependencies
        run: pip install -e .
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy tg_cal_reminder

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install project and test dependencies
        run: |
          pip install -e .
          pip install pytest pytest-asyncio pytest-cov respx
      - name: Run unit tests
        run: pytest --cov=tg_cal_reminder
      - name: Run integration tests
        run: pytest integration_tests --cov=tg_cal_reminder         
