on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install ruff
      - name: Run Ruff
        run: ruff check

  typecheck:
    name: Type-check with mypy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install mypy
      - name: Run mypy
        run: mypy tg_cal_reminder

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: typecheck        # ensure lint+typecheck pass first
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Hatch
        run: pip install hatchling hatch
      - name: Install project dependencies
        run: hatch env create --no-build
      - name: Run tests
        run: hatch run test
      - name: Run integration tests
        run: hatch run integration         